# Ex5A NumPy Fundamentals

This exercise introduces NumPy array basics, includ data types, transposing, and working with multidim

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ['apple', 'banana', 'cherry', 'date']

In [4]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'grape']


In [5]:
print(arr_1.dtype)

<U6


In [13]:
# <U6 means its a Unicode string array, each element can hold up to 6 characters

In [6]:
arr_2 = np.array([
    [10, 11, 12],
    [13, 14,15]
])

print(arr_2)

[[10 11 12]
 [13 14 15]]


In [7]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [8]:
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [14]:
# arr_2.T does not change arr_2

In [10]:
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

print(arr_3)

[[1 3 5]
 [2 4 6]]


In [11]:
arr_4 = np.array([arr_3[0,2],arr_3[1,1]])
print(arr_4)

[5 4]


In [12]:
arr_5 = np.ones((2, 2, 2))
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
