# Exercise 1.A NumPy: Manipulating Arrays 

In [12]:
import numpy as np

## Looping Through Arrays

In [13]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [14]:
for x in arrA:
    x = x*2
    print(x)

[22 24 26]
[28 30 32]


In [15]:
for x in arrA:
    for y in x:
        y = y*2
        print(y)

22
24
26
28
30
32


These two are differnt because the first for loop is printing the arrays as two seperate arrys , but the second for loop is printing th values in the arrays.

In [16]:
for x in arrA:
    loop_result = x * 2
    for y in x:
        print(loop_result) 
# this is differnt then before because its looping 3 times for each number in the array.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [17]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [18]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [19]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [20]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

# ValueError: all input arrays must have the same shape
# we get this error because joined_array_1 is in axis 0 yet joined_array_2 is in axis 1

ValueError: all input arrays must have the same shape

In [ ]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

In [ ]:
another_2 = np.concatenate((joined_array_1, arrA), axis = 1)
print(another_2)

# Since joinedarray1 is bigger then arrA it can only br concatenated at axis = 0 

In [ ]:
harrA = np.hstack((arrA, arrA)) # stacking arrA on top of arrA
print(harrA)
darrA = np.dstack((arrA, arrA)) # stacking alomg height and depth
print(darrA)
varrA = np.vstack((arrA, arrA)) # stacking vertically on the axis of the array
print(varrA)

## Splitting Arrays

In [ ]:
splitsky =  np.array_split( joined_array_1, 2) # splits into two arrays both in the secound dimension
print(splitsky)

In [ ]:
spliterino = np.array_split( joined_array_1, 3) # there are 3 arrays all in secound dimension
print(spliterino)

## Searching and Replacing Array Values.

In [21]:
result_1 = np.where(arrA % 2 == 0,arrA,'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


 ## Sorting and Filtering Arrays

In [22]:
arrB = np.array([[7,6],
                 [13,5],
                 [7,3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [23]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [24]:
z = arrB >= 7
arrD = arrB[z]
print(arrD)

[ 7 13  7]
