# Exercise 1.B NumPy Random

In [1]:
import numpy as np

 ## Generating Random Numbers

In [3]:
r_1 = np.random.randint(1, 20, size=(2))
print(r_1)

[15  4]


In [7]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[4 8]]


In [9]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.28583472]
 [0.70196598]]


In [10]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[25 73 22 34 83]
 [92 27 98 71 67]
 [93 73 64 68 95]
 [63 63 99 94 47]]


In [11]:
r_5 = np.random.rand(4,5)
print(r_5)

[[0.92481049 0.3048055  0.1802119  0.13624566 0.84990749]
 [0.00148353 0.73904037 0.00130244 0.20458259 0.92278361]
 [0.8264727  0.00601617 0.06157661 0.04160439 0.84741878]
 [0.90222715 0.97187179 0.23356062 0.80066358 0.29483646]]


 ## Generating Random Choices from an Array

In [12]:
students = np.array(['Dahlia',
                     'Destiney',
                     'Brandon',
                     'Kevin',
                     'Luis',
                     'Sthefanine',
                     'Edmund',
                     'Hritik',
                     'Natalia',
                     'Jeremiah'])

In [27]:
call_on = np.random.choice(students)
print(call_on)

Natalia


In [28]:
breakout_groups = np.random.choice(students, size=(3,4)) # this isnt a good way to make groups because people can be repeated in the groups
print(breakout_groups)

[['Destiney' 'Brandon' 'Brandon' 'Jeremiah']
 ['Brandon' 'Natalia' 'Natalia' 'Hritik']
 ['Brandon' 'Destiney' 'Brandon' 'Kevin']]


In [34]:
call_on_weighted = np.random.choice(students,p = [0.0, 0.3, 0.1, 0.2, 0.0, 0.1,0.0,0.1,0.1, 0.1], size = (5))
print(call_on_weighted) # Dahlia,Luis,Edmund=0%;Brandon,Sthefanine,Hritik,'Natalia,Jeremiah =10%; Destiney = 30%; Kevin = 20%

['Sthefanine' 'Jeremiah' 'Jeremiah' 'Hritik' 'Kevin']


## Generating a Normal Distribution


In [35]:
bell_curve =np.random.normal(loc=10,scale=5, size=(4,5)) 
print(bell_curve)

[[15.31368662 10.88604226 19.16931832 12.44200151  9.85971905]
 [ 8.48548833 14.15403571 16.10904919  7.88401088  7.63606045]
 [10.10004883 23.95819158 11.32499749  7.94103554  6.91040522]
 [ 8.18533512 11.24306277 12.15556985  9.92366394 12.63312652]]
