# Exercise 1.C Performing operations on arrays 

In [46]:
import numpy as np

## Sample Arrays

In [47]:
r_1 = np.random.randint(1, 20, size=(2))
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4,5)

## Permutations

In [48]:
print(r_4)

[[29 71 79 42 33]
 [96 52 66 90 54]
 [28 58 83 68 73]
 [56 71 24 57 20]]


In [49]:
np.random.shuffle(r_4)
print(r_4)

[[96 52 66 90 54]
 [56 71 24 57 20]
 [29 71 79 42 33]
 [28 58 83 68 73]]


these two cells of code are in decending order

In [50]:
new_shuffle = (np.random.permutation(r_4))
print(r_4)
print(new_shuffle)

[[96 52 66 90 54]
 [56 71 24 57 20]
 [29 71 79 42 33]
 [28 58 83 68 73]]
[[28 58 83 68 73]
 [29 71 79 42 33]
 [96 52 66 90 54]
 [56 71 24 57 20]]


the differnce between shuffle and permutation is that permutation is completely random when shuffle isnt.

 ## Mathematical Operations

In [51]:
print(r_1)
print(r_1.shape)
print(r_2)
print(r_2.shape)
r_12 = np.add(r_1,r_2)
print(r_12)
print(r_12.shape)

[7 9]
(2,)
[[ 1 18]]
(1, 2)
[[ 8 27]]
(1, 2)


In [52]:
print(r_1)
print(r_1.shape)
print(r_3)
print(r_3.shape)
r_13 = np.add(r_1,r_3)
print(r_13)
print(r_13.shape)

[7 9]
(2,)
[[0.17803489]
 [0.28428932]]
(2, 1)
[[7.17803489 9.17803489]
 [7.28428932 9.28428932]]
(2, 2)


In [53]:
print(r_2)
print(r_2.shape)
print(r_4)
print(r_4.shape)
r_24 = np.add(r_2,r_4)
print(r_24)
print(r_24.shape)

[[ 1 18]]
(1, 2)
[[96 52 66 90 54]
 [56 71 24 57 20]
 [29 71 79 42 33]
 [28 58 83 68 73]]
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

this creates an error because the array shapes are too differnt.

In [54]:
np.add(r_1,r_4)

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [55]:
np.add(r_3,r_4)

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Again the shapes are too differnt to add together

In [56]:
print(np.add(np.array([1]),r_4))

[[97 53 67 91 55]
 [57 72 25 58 21]
 [30 72 80 43 34]
 [29 59 84 69 74]]


In [57]:
print(np.add(np.array([[1]]), r_4))

[[97 53 67 91 55]
 [57 72 25 58 21]
 [30 72 80 43 34]
 [29 59 84 69 74]]


In [58]:
print(np.add(np.array([1,1,1,1,1]), r_4))

[[97 53 67 91 55]
 [57 72 25 58 21]
 [30 72 80 43 34]
 [29 59 84 69 74]]


In [59]:
print(np.add(np.array([[1],[1]]), r_4)) # ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

if the shapes are too differnt it cant be added together since there arent enough numbers to add with. The shape is determind by how many rows and columns

## Rounding

In [60]:
print(r_3)

[[0.17803489]
 [0.28428932]]


In [61]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [62]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [63]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [64]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [65]:
print(np.round(r_3,2))

[[0.18]
 [0.28]]


 ## Cumulative Operations

In [66]:
print(r_4)

[[96 52 66 90 54]
 [56 71 24 57 20]
 [29 71 79 42 33]
 [28 58 83 68 73]]


In [67]:
np.sum(r_4)

np.int64(1150)

In [68]:
np.sum(r_4,axis=0)

array([209, 252, 252, 257, 180])

In [69]:
np.sum(r_4,axis=1)

array([358, 228, 254, 310])

In [70]:
np.cumsum(r_4)

array([  96,  148,  214,  304,  358,  414,  485,  509,  566,  586,  615,
        686,  765,  807,  840,  868,  926, 1009, 1077, 1150])

In [71]:
np.cumsum(r_4, axis=0)

array([[ 96,  52,  66,  90,  54],
       [152, 123,  90, 147,  74],
       [181, 194, 169, 189, 107],
       [209, 252, 252, 257, 180]])

## Grocery Problem

In [72]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print("bag1:", bag1)
print("bag2:", bag2)

bag1: [2 3 4 0]
bag2: [4 0 1 2]


In [73]:
bag_1_total = np.sum(bag1)
bag_2_total = np.sum(bag2)
print(f'The first bag contains {bag_1_total} items, and the second bag contains {bag_2_total} items.')

The first bag contains 9 items, and the second bag contains 7 items.


In [75]:
total_bags = np.add(bag1,bag2)

print(f'There are {total_bags[0]} vegetables, {total_bags[1]} fruits, {total_bags[2]} boxes of snacks, and {total_bags[3]} beverages in the two grocery bags.')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [77]:
ali = np.array([5,4,6,4,2])

In [78]:
ben = np.array([0,5,5,3,4])

In [79]:
carla = np.array([3,6,0,3,4])

In [80]:
all_knocks = np.array([ali,ben,carla])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [90]:
person_total = np.sum(all_knocks, axis = 1)
group_total = np.sum(all_knocks)

print(person_total)
print(group_total)

[21 17 16]
54


In [91]:
day_total = np.sum(all_knocks, axis = 0)
votes = np.cumsum(day_total) * 0.5
print(votes)

[ 4.  11.5 17.  22.  27. ]
